name: Trigger auto deployment for sitbotapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sitbotapi-AutoDeployTrigger-2269c9c7-bd95-436c-8a99-5b1e8b5f2e47.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SITBOTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SITBOTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SITBOTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: sirbotregistry.azurecr.io
          registryUsername: ${{ secrets.SITBOTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SITBOTAPI_REGISTRY_PASSWORD }}
          containerAppName: sitbotapi
          resourceGroup: datascience
          imageToBuild: sirbotregistry.azurecr.io/sitbotapi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


